CREATE TABLE PROJECT (
  ID UUID PRIMARY KEY,
  PROJECT_NAME VARCHAR(255),
  BASEPATH CLOB
);

CREATE TABLE LICENSE (
  ID UUID PRIMARY KEY,
  PRIORITY INT,
  LICENSE_TYPE VARCHAR(255),
  LICENSE_TEXT CLOB,
  LICENSE_NAME VARCHAR(255),
  DETAILS_URL VARCHAR(2048),
  MODIFIED BOOLEAN,
  CURATED BOOLEAN,
  IS_SPDX BOOLEAN
);

CREATE TABLE VULNERABILITY (
  ID UUID PRIMARY KEY
);

CREATE TABLE SOFTWARE_COMPONENT (
  ID UUID PRIMARY KEY,
  SOFTWARE_COMPONENT_NAME VARCHAR(255) NOT NULL,
  VERSION VARCHAR(255) NOT NULL,
  PURL VARCHAR(2048),
  CURATED BOOLEAN,
  DETAILS_URL VARCHAR(2048)
);

CREATE TABLE INVENTORY_ITEM (
  ID UUID PRIMARY KEY,
  INVENTORY_NAME CLOB,
  SIZE INT,
  SPDX_ID CLOB,
  LINKING VARCHAR(255),
  PRIORITY INT,
  CONSPICUOUS BOOLEAN,
  EXTERNAL_NOTES CLOB,
  PARENT_INVENTORY_ITEM_ID UUID,
  SOFTWARE_COMPONENT_ID UUID,
  WAS_COMBINED BOOLEAN,
  CURATED BOOLEAN,
  PROJECT_ID UUID NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CONSTRAINT FK_INV_PARENT FOREIGN KEY (PARENT_INVENTORY_ITEM_ID) REFERENCES INVENTORY_ITEM(ID),
  CONSTRAINT FK_INV_SOFTWARE_COMPONENT FOREIGN KEY (SOFTWARE_COMPONENT_ID) REFERENCES SOFTWARE_COMPONENT(ID),
  CONSTRAINT FK_INV_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE CODE_LOCATION (
  ID UUID PRIMARY KEY,
  INVENTORYITEM_ID UUID,
  FILE_PATH CLOB,
  LINE_NUMBER INT,
  LINE_NUMBER_TO INT,
  CONSTRAINT FK_CODELOCATION_INVENTORYITEM FOREIGN KEY (INVENTORYITEM_ID) REFERENCES INVENTORY_ITEM(ID)
);

CREATE TABLE COPYRIGHT (
  ID UUID PRIMARY KEY,
  SOFTWARECOMPONENT_ID UUID,
  COPYRIGHT_TEXT CLOB,
  CODE_LOCATION_ID UUID,
  CURATED BOOLEAN,
  GARBAGE BOOLEAN,
  CONSTRAINT FK_COPYRIGHT_SOF FOREIGN KEY (SOFTWARECOMPONENT_ID) REFERENCES SOFTWARE_COMPONENT(ID)
);

CREATE TABLE SOFTWARE_COMPONENT_LICENSE_LINK (
  SOFTWARE_COMPONENT_ID UUID NOT NULL,
  LICENSE_ID UUID NOT NULL,
  CONSTRAINT PK_SC_LICENSE_LINK PRIMARY KEY (SOFTWARE_COMPONENT_ID, LICENSE_ID),
  CONSTRAINT FK_SC_LICENSE_SC FOREIGN KEY (SOFTWARE_COMPONENT_ID) REFERENCES SOFTWARE_COMPONENT(ID) ON DELETE CASCADE,
  CONSTRAINT FK_SC_LICENSE_LICENSE FOREIGN KEY (LICENSE_ID) REFERENCES LICENSE(ID) ON DELETE CASCADE
);

CREATE TABLE SOFTWARE_COMPONENT_VULNERABILITY_LINK (
  SOFTWARE_COMPONENT_ID UUID NOT NULL,
  VULNERABILITY_ID UUID NOT NULL,
  CONSTRAINT PK_SC_VULN_LINK PRIMARY KEY (SOFTWARE_COMPONENT_ID, VULNERABILITY_ID),
  CONSTRAINT FK_SC_VULN_SC FOREIGN KEY (SOFTWARE_COMPONENT_ID) REFERENCES SOFTWARE_COMPONENT(ID) ON DELETE CASCADE,
  CONSTRAINT FK_SC_VULN_VULN FOREIGN KEY (VULNERABILITY_ID) REFERENCES VULNERABILITY(ID) ON DELETE CASCADE
);
